### ISSUE TITLE
README instructions reference a 404 repo

### ISSUE THREAD

**Issue by davew-msft** [Azure-Samples/IoTDemos#30]
https://github.com/Azure-Samples/IoTDemos/blob/master/RetailDemo/README.md says to clone this:  git clone https://github.com/Teodelas/RetailDemo.git which gives a 404.  I think you want to clone this:  https://github.com/Azure-Samples/IoTDemos.git

@Teodelas most likely

**Comment by davew-msft** [comment]
git lfs pull subsequently fails with 404 errors.  My guess is that's because I'm not cloning the repo you think I am.

**Comment by Teodelas** [comment]
Good catch.  Fixed.

Thank you!
